
apiVersion: v1
kind: Service
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  type: LoadBalancer   # change to NodePort if you don't want an external LB
  selector:
    app: tomcat
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
